"""add column updated_at to Manos table

Revision ID: 4ced4103ec4f
Revises: 8c5723c5b6f1
Create Date: 2025-04-22 03:19:15.695023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ced4103ec4f'
down_revision: Union[str, None] = '8c5723c5b6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('manos', schema=None) as batch_op:
        """Upgrade schema."""
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manos', schema=None) as batch_op: 
        batch_op.drop_column('updated_at')
    # ### end Alembic commands ###
